export enum RhythmSortType {
    HIGHEST_CONFIDENCE = 'HIGHEST_CONFIDENCE',
    LONGEST = 'LONGEST',
    FASTEST = 'FASTEST',
    FASTEST_AVERAGE = 'FASTEST_AVERAGE',
    SLOWEST = 'SLOWEST',
	FASTEST_MDN = 'FASTEST_MDN',
    LONGEST_SYMPTOMATIC = 'LONGEST_SYMPTOMATIC',
    MDN = 'MDN',
    SYMPTOMATIC = 'SYMPTOMATIC',
    SECOND_FASTEST = 'SECOND_FASTEST',
    SECOND_LONGEST = 'SECOND_LONGEST',
    SECOND_FASTEST_AVERAGE = 'SECOND_FASTEST_AVERAGE'
}